server:
  port: 9201

service-url:
  user-service: http://localhost:8201

spring:
  cloud:
    gateway:
      routes:
#          设置
        - id: path_route
#          uri: ${service-url.user-service}/user/{id}
          uri: lb://user-service/user/{id}
          predicates:
            - Path=/user/{id}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug