server:
  port: 8201

spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
  #设置Sleuth的抽样收集概率
  sleuth:
    sampler:
      probability: 0.1

  cloud:
    nacos:
      discovery:
        # Nacos地址
        server-addr: http://localhost:8848

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8001/eureka/

