server:
  port: 8401

spring:
  application:
    name: hystrix-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # 注册到另一个Eureka注册中心
      defaultZone: http://localhost:8001/eureka/

management:
  endpoints:
    web:
      exposure:
        #暴露hystrix监控端点
        include: 'hystrix.stream'

service-url:
  user-service: http://user-service
